import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  console.log(styles)
  return (
    <>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container} >
        <main className={styles.main}>
          <div className={styles.heroSection}>
            <div className={styles.heroText}>
              <h1 className={styles.title}>
                Hunting Coders
              </h1>
              <p className={styles.description}>
                A Blog for hunting coder by hunting corder
              </p>
            </div>
          </div>
          <hr />
          {/* <Image src="/assets/hd_bg.jpg" alt="" width={400} height={220} /> */}
          <img src="/assets/hd_bg.jpg" alt="Hunting Coder" width={400} height={220} />
          <h2>Latest Blogs</h2>
          <hr />
          <h3>How to learn JavaScript?</h3>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corporis mollitia odio explicabo molestiae ipsam facere repudiandae quod, cumque sequi modi.</p>
          <h3>How to learn JavaScript?</h3>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corporis mollitia odio explicabo molestiae ipsam facere repudiandae quod, cumque sequi modi.</p>
          <h3>How to learn JavaScript?</h3>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corporis mollitia odio explicabo molestiae ipsam facere repudiandae quod, cumque sequi modi.</p>
        </main>
      </div>
    </>
  )
}
