import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  console.log(styles)
  return (
    <div className={styles.container} >
      <style jsx global>
        {`
          .hero{
          color: blue;
          }
          .blogItem img{
            border-radius: 7px;
            box-shadow: 4px 5px 15px #3333;
            margin-top: 20px;
          }
          `
        }
      </style>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coders
        </h1>
        <span className='hero'>This is hero text</span>
        <p className={styles.description}>
          A Blog for hunting coder bybb hunting corder
        </p>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div >
  )
}
